<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base.proto

namespace Vcloud\Models\GPBMetadata;

class Base
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0af4010a0a626173652e70726f746f121256636c6f75642e4d6f64656c732e426173652299010a10526573706f6e73654d6574616461746112110a09526571756573744964180120012809120e0a06416374696f6e180220012809120f0a0756657273696f6e180320012809120f0a0753657276696365180420012809120e0a06526567696f6e18052001280912300a054572726f7218062001280b32212e56636c6f75642e4d6f64656c732e426173652e526573706f6e73654572726f72222e0a0d526573706f6e73654572726f72120c0a04436f6465180120012809120f0a074d657373616765180220012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

