<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base.proto

namespace Vcloud\Models\Base;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Vcloud.Models.Base.ResponseError</code>
 */
class ResponseError extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Code = 1;</code>
     */
    protected $Code = '';
    /**
     * Generated from protobuf field <code>string Message = 2;</code>
     */
    protected $Message = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Code
     *     @type string $Message
     * }
     */
    public function __construct($data = NULL) {
        \Vcloud\Models\GPBMetadata\Base::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string Code = 1;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->Code;
    }

    /**
     * Generated from protobuf field <code>string Code = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->Code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Message = 2;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->Message;
    }

    /**
     * Generated from protobuf field <code>string Message = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->Message = $var;

        return $this;
    }

}

