<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base.proto

namespace Vcloud\Models\Base;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Vcloud.Models.Base.ResponseMetadata</code>
 */
class ResponseMetadata extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string RequestId = 1;</code>
     */
    protected $RequestId = '';
    /**
     * Generated from protobuf field <code>string Action = 2;</code>
     */
    protected $Action = '';
    /**
     * Generated from protobuf field <code>string Version = 3;</code>
     */
    protected $Version = '';
    /**
     * Generated from protobuf field <code>string Service = 4;</code>
     */
    protected $Service = '';
    /**
     * Generated from protobuf field <code>string Region = 5;</code>
     */
    protected $Region = '';
    /**
     * Generated from protobuf field <code>.Vcloud.Models.Base.ResponseError Error = 6;</code>
     */
    protected $Error = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $RequestId
     *     @type string $Action
     *     @type string $Version
     *     @type string $Service
     *     @type string $Region
     *     @type \Vcloud\Models\Base\ResponseError $Error
     * }
     */
    public function __construct($data = NULL) {
        \Vcloud\Models\GPBMetadata\Base::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string RequestId = 1;</code>
     * @return string
     */
    public function getRequestId()
    {
        return $this->RequestId;
    }

    /**
     * Generated from protobuf field <code>string RequestId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRequestId($var)
    {
        GPBUtil::checkString($var, True);
        $this->RequestId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Action = 2;</code>
     * @return string
     */
    public function getAction()
    {
        return $this->Action;
    }

    /**
     * Generated from protobuf field <code>string Action = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAction($var)
    {
        GPBUtil::checkString($var, True);
        $this->Action = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Version = 3;</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->Version;
    }

    /**
     * Generated from protobuf field <code>string Version = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->Version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Service = 4;</code>
     * @return string
     */
    public function getService()
    {
        return $this->Service;
    }

    /**
     * Generated from protobuf field <code>string Service = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setService($var)
    {
        GPBUtil::checkString($var, True);
        $this->Service = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Region = 5;</code>
     * @return string
     */
    public function getRegion()
    {
        return $this->Region;
    }

    /**
     * Generated from protobuf field <code>string Region = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setRegion($var)
    {
        GPBUtil::checkString($var, True);
        $this->Region = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Vcloud.Models.Base.ResponseError Error = 6;</code>
     * @return \Vcloud\Models\Base\ResponseError
     */
    public function getError()
    {
        return $this->Error;
    }

    /**
     * Generated from protobuf field <code>.Vcloud.Models.Base.ResponseError Error = 6;</code>
     * @param \Vcloud\Models\Base\ResponseError $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkMessage($var, \Vcloud\Models\Base\ResponseError::class);
        $this->Error = $var;

        return $this;
    }

}

