<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vod_media.proto

namespace Vcloud\Models\Vod;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Vcloud.Models.Vod.GetRecommendedPostersRequest</code>
 */
class GetRecommendedPostersRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *视频ID列表
     *
     * Generated from protobuf field <code>repeated string Vids = 1;</code>
     */
    private $Vids;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $Vids
     *          视频ID列表
     * }
     */
    public function __construct($data = NULL) {
        \Vcloud\Models\GPBMetadata\VodMedia::initOnce();
        parent::__construct($data);
    }

    /**
     *视频ID列表
     *
     * Generated from protobuf field <code>repeated string Vids = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getVids()
    {
        return $this->Vids;
    }

    /**
     *视频ID列表
     *
     * Generated from protobuf field <code>repeated string Vids = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setVids($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->Vids = $arr;

        return $this;
    }

}

