<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vod_media.proto

namespace Vcloud\Models\Vod;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Vcloud.Models.Vod.GetVideoInfosData</code>
 */
class GetVideoInfosData extends \Google\Protobuf\Internal\Message
{
    /**
     *视频信息列表
     *
     * Generated from protobuf field <code>repeated .Vcloud.Models.Vod.VideoInfo VideoInfoList = 1;</code>
     */
    private $VideoInfoList;
    /**
     *不存在的视频VID列表
     *
     * Generated from protobuf field <code>repeated string NotExistVids = 2;</code>
     */
    private $NotExistVids;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Vcloud\Models\Vod\VideoInfo[]|\Google\Protobuf\Internal\RepeatedField $VideoInfoList
     *          视频信息列表
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $NotExistVids
     *          不存在的视频VID列表
     * }
     */
    public function __construct($data = NULL) {
        \Vcloud\Models\GPBMetadata\VodMedia::initOnce();
        parent::__construct($data);
    }

    /**
     *视频信息列表
     *
     * Generated from protobuf field <code>repeated .Vcloud.Models.Vod.VideoInfo VideoInfoList = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getVideoInfoList()
    {
        return $this->VideoInfoList;
    }

    /**
     *视频信息列表
     *
     * Generated from protobuf field <code>repeated .Vcloud.Models.Vod.VideoInfo VideoInfoList = 1;</code>
     * @param \Vcloud\Models\Vod\VideoInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setVideoInfoList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Vcloud\Models\Vod\VideoInfo::class);
        $this->VideoInfoList = $arr;

        return $this;
    }

    /**
     *不存在的视频VID列表
     *
     * Generated from protobuf field <code>repeated string NotExistVids = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNotExistVids()
    {
        return $this->NotExistVids;
    }

    /**
     *不存在的视频VID列表
     *
     * Generated from protobuf field <code>repeated string NotExistVids = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNotExistVids($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->NotExistVids = $arr;

        return $this;
    }

}

