<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vod_play.proto

namespace Vcloud\Models\Vod;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Vcloud.Models.Vod.Test</code>
 */
class Test extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.google.protobuf.Int32Value a = 1;</code>
     */
    protected $a = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Int32Value $a
     * }
     */
    public function __construct($data = NULL) {
        \Vcloud\Models\GPBMetadata\VodPlay::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Int32Value a = 1;</code>
     * @return \Google\Protobuf\Int32Value
     */
    public function getA()
    {
        return $this->a;
    }

    /**
     * Returns the unboxed value from <code>getA()</code>

     * Generated from protobuf field <code>.google.protobuf.Int32Value a = 1;</code>
     * @return int|null
     */
    public function getAUnwrapped()
    {
        return $this->readWrapperValue("a");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Int32Value a = 1;</code>
     * @param \Google\Protobuf\Int32Value $var
     * @return $this
     */
    public function setA($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Int32Value::class);
        $this->a = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\Int32Value object.

     * Generated from protobuf field <code>.google.protobuf.Int32Value a = 1;</code>
     * @param int|null $var
     * @return $this
     */
    public function setAUnwrapped($var)
    {
        $this->writeWrapperValue("a", $var);
        return $this;}

}

