<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vod/business/vod_media.proto

namespace Vcloud\Models\Vod\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Vcloud.Models.Vod.GetRecPostersData</code>
 */
class GetRecPostersData extends \Google\Protobuf\Internal\Message
{
    /**
     *封面图信息
     *
     * Generated from protobuf field <code>repeated .Vcloud.Models.Vod.StoreUriGroup StoreUriGroups = 1;</code>
     */
    private $StoreUriGroups;
    /**
     *不存在的视频VID列表
     *
     * Generated from protobuf field <code>repeated string NotExistVids = 2;</code>
     */
    private $NotExistVids;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Vcloud\Models\Vod\Business\StoreUriGroup[]|\Google\Protobuf\Internal\RepeatedField $StoreUriGroups
     *          封面图信息
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $NotExistVids
     *          不存在的视频VID列表
     * }
     */
    public function __construct($data = NULL) {
        \Vcloud\Models\GPBMetadata\VodMedia::initOnce();
        parent::__construct($data);
    }

    /**
     *封面图信息
     *
     * Generated from protobuf field <code>repeated .Vcloud.Models.Vod.StoreUriGroup StoreUriGroups = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStoreUriGroups()
    {
        return $this->StoreUriGroups;
    }

    /**
     *封面图信息
     *
     * Generated from protobuf field <code>repeated .Vcloud.Models.Vod.StoreUriGroup StoreUriGroups = 1;</code>
     * @param \Vcloud\Models\Vod\Business\StoreUriGroup[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStoreUriGroups($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Vcloud\Models\Vod\Business\StoreUriGroup::class);
        $this->StoreUriGroups = $arr;

        return $this;
    }

    /**
     *不存在的视频VID列表
     *
     * Generated from protobuf field <code>repeated string NotExistVids = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNotExistVids()
    {
        return $this->NotExistVids;
    }

    /**
     *不存在的视频VID列表
     *
     * Generated from protobuf field <code>repeated string NotExistVids = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNotExistVids($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->NotExistVids = $arr;

        return $this;
    }

}

