<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vod/business/vod_upload.proto

namespace Vcloud\Models\Vod\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Vcloud.Models.Vod.QueryUploadResult</code>
 */
class QueryUploadResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Vcloud.Models.Vod.URLSet VideoInfoList = 1;</code>
     */
    private $VideoInfoList;
    /**
     * Generated from protobuf field <code>repeated string NotExistJobIds = 2;</code>
     */
    private $NotExistJobIds;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Vcloud\Models\Vod\Business\URLSet[]|\Google\Protobuf\Internal\RepeatedField $VideoInfoList
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $NotExistJobIds
     * }
     */
    public function __construct($data = NULL) {
        \Vcloud\Models\GPBMetadata\VodUpload::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Vcloud.Models.Vod.URLSet VideoInfoList = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getVideoInfoList()
    {
        return $this->VideoInfoList;
    }

    /**
     * Generated from protobuf field <code>repeated .Vcloud.Models.Vod.URLSet VideoInfoList = 1;</code>
     * @param \Vcloud\Models\Vod\Business\URLSet[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setVideoInfoList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Vcloud\Models\Vod\Business\URLSet::class);
        $this->VideoInfoList = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string NotExistJobIds = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNotExistJobIds()
    {
        return $this->NotExistJobIds;
    }

    /**
     * Generated from protobuf field <code>repeated string NotExistJobIds = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNotExistJobIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->NotExistJobIds = $arr;

        return $this;
    }

}

