<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vod/business/vod_workflow.proto

namespace Vcloud\Models\Vod\Business;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Vcloud.Models.Vod.WorkflowParams</code>
 */
class WorkflowParams extends \Google\Protobuf\Internal\Message
{
    /**
     * 覆盖参数
     *
     * Generated from protobuf field <code>.Vcloud.Models.Vod.OverrideParams OverrideParams = 1;</code>
     */
    protected $OverrideParams = null;
    /**
     * 条件变量
     *
     * Generated from protobuf field <code>map<string, bool> Condition = 2;</code>
     */
    private $Condition;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Vcloud\Models\Vod\Business\OverrideParams $OverrideParams
     *           覆盖参数
     *     @type array|\Google\Protobuf\Internal\MapField $Condition
     *           条件变量
     * }
     */
    public function __construct($data = NULL) {
        \Vcloud\Models\GPBMetadata\VodWorkflow::initOnce();
        parent::__construct($data);
    }

    /**
     * 覆盖参数
     *
     * Generated from protobuf field <code>.Vcloud.Models.Vod.OverrideParams OverrideParams = 1;</code>
     * @return \Vcloud\Models\Vod\Business\OverrideParams
     */
    public function getOverrideParams()
    {
        return $this->OverrideParams;
    }

    /**
     * 覆盖参数
     *
     * Generated from protobuf field <code>.Vcloud.Models.Vod.OverrideParams OverrideParams = 1;</code>
     * @param \Vcloud\Models\Vod\Business\OverrideParams $var
     * @return $this
     */
    public function setOverrideParams($var)
    {
        GPBUtil::checkMessage($var, \Vcloud\Models\Vod\Business\OverrideParams::class);
        $this->OverrideParams = $var;

        return $this;
    }

    /**
     * 条件变量
     *
     * Generated from protobuf field <code>map<string, bool> Condition = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getCondition()
    {
        return $this->Condition;
    }

    /**
     * 条件变量
     *
     * Generated from protobuf field <code>map<string, bool> Condition = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setCondition($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::BOOL);
        $this->Condition = $arr;

        return $this;
    }

}

