<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vod_upload.proto

namespace Vcloud\Models\Vod;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Vcloud.Models.Vod.SourceInfo</code>
 */
class SourceInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string StoreUri = 1;</code>
     */
    protected $StoreUri = '';
    /**
     * Generated from protobuf field <code>string Md5 = 2;</code>
     */
    protected $Md5 = '';
    /**
     * Generated from protobuf field <code>int64 Width = 3;</code>
     */
    protected $Width = 0;
    /**
     * Generated from protobuf field <code>int64 Height = 4;</code>
     */
    protected $Height = 0;
    /**
     * Generated from protobuf field <code>float Duration = 5;</code>
     */
    protected $Duration = 0.0;
    /**
     * Generated from protobuf field <code>float Bitrate = 6;</code>
     */
    protected $Bitrate = 0.0;
    /**
     * Generated from protobuf field <code>string Format = 7;</code>
     */
    protected $Format = '';
    /**
     * Generated from protobuf field <code>int64 Size = 8;</code>
     */
    protected $Size = 0;
    /**
     * Generated from protobuf field <code>string FileType = 9;</code>
     */
    protected $FileType = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $StoreUri
     *     @type string $Md5
     *     @type int|string $Width
     *     @type int|string $Height
     *     @type float $Duration
     *     @type float $Bitrate
     *     @type string $Format
     *     @type int|string $Size
     *     @type string $FileType
     * }
     */
    public function __construct($data = NULL) {
        \Vcloud\Models\GPBMetadata\VodUpload::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string StoreUri = 1;</code>
     * @return string
     */
    public function getStoreUri()
    {
        return $this->StoreUri;
    }

    /**
     * Generated from protobuf field <code>string StoreUri = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStoreUri($var)
    {
        GPBUtil::checkString($var, True);
        $this->StoreUri = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Md5 = 2;</code>
     * @return string
     */
    public function getMd5()
    {
        return $this->Md5;
    }

    /**
     * Generated from protobuf field <code>string Md5 = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMd5($var)
    {
        GPBUtil::checkString($var, True);
        $this->Md5 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 Width = 3;</code>
     * @return int|string
     */
    public function getWidth()
    {
        return $this->Width;
    }

    /**
     * Generated from protobuf field <code>int64 Width = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setWidth($var)
    {
        GPBUtil::checkInt64($var);
        $this->Width = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 Height = 4;</code>
     * @return int|string
     */
    public function getHeight()
    {
        return $this->Height;
    }

    /**
     * Generated from protobuf field <code>int64 Height = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setHeight($var)
    {
        GPBUtil::checkInt64($var);
        $this->Height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float Duration = 5;</code>
     * @return float
     */
    public function getDuration()
    {
        return $this->Duration;
    }

    /**
     * Generated from protobuf field <code>float Duration = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setDuration($var)
    {
        GPBUtil::checkFloat($var);
        $this->Duration = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float Bitrate = 6;</code>
     * @return float
     */
    public function getBitrate()
    {
        return $this->Bitrate;
    }

    /**
     * Generated from protobuf field <code>float Bitrate = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setBitrate($var)
    {
        GPBUtil::checkFloat($var);
        $this->Bitrate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Format = 7;</code>
     * @return string
     */
    public function getFormat()
    {
        return $this->Format;
    }

    /**
     * Generated from protobuf field <code>string Format = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setFormat($var)
    {
        GPBUtil::checkString($var, True);
        $this->Format = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 Size = 8;</code>
     * @return int|string
     */
    public function getSize()
    {
        return $this->Size;
    }

    /**
     * Generated from protobuf field <code>int64 Size = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkInt64($var);
        $this->Size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string FileType = 9;</code>
     * @return string
     */
    public function getFileType()
    {
        return $this->FileType;
    }

    /**
     * Generated from protobuf field <code>string FileType = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setFileType($var)
    {
        GPBUtil::checkString($var, True);
        $this->FileType = $var;

        return $this;
    }

}

