<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vod/response/response_vod.proto

namespace Vcloud\Models\Vod\Response;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Vcloud.Models.Vod.VodGetPlayInfoResponse</code>
 */
class VodGetPlayInfoResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * 响应通用信息
     *
     * Generated from protobuf field <code>.Vcloud.Models.Base.ResponseMetadata ResponseMetadata = 1;</code>
     */
    protected $ResponseMetadata = null;
    /**
     * 响应结果
     *
     * Generated from protobuf field <code>.Vcloud.Models.Vod.VodGetPlayInfoResult Result = 2;</code>
     */
    protected $Result = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Vcloud\Models\Base\ResponseMetadata $ResponseMetadata
     *           响应通用信息
     *     @type \Vcloud\Models\Vod\Business\VodGetPlayInfoResult $Result
     *           响应结果
     * }
     */
    public function __construct($data = NULL) {
        \Vcloud\Models\GPBMetadata\ResponseVod::initOnce();
        parent::__construct($data);
    }

    /**
     * 响应通用信息
     *
     * Generated from protobuf field <code>.Vcloud.Models.Base.ResponseMetadata ResponseMetadata = 1;</code>
     * @return \Vcloud\Models\Base\ResponseMetadata
     */
    public function getResponseMetadata()
    {
        return $this->ResponseMetadata;
    }

    /**
     * 响应通用信息
     *
     * Generated from protobuf field <code>.Vcloud.Models.Base.ResponseMetadata ResponseMetadata = 1;</code>
     * @param \Vcloud\Models\Base\ResponseMetadata $var
     * @return $this
     */
    public function setResponseMetadata($var)
    {
        GPBUtil::checkMessage($var, \Vcloud\Models\Base\ResponseMetadata::class);
        $this->ResponseMetadata = $var;

        return $this;
    }

    /**
     * 响应结果
     *
     * Generated from protobuf field <code>.Vcloud.Models.Vod.VodGetPlayInfoResult Result = 2;</code>
     * @return \Vcloud\Models\Vod\Business\VodGetPlayInfoResult
     */
    public function getResult()
    {
        return $this->Result;
    }

    /**
     * 响应结果
     *
     * Generated from protobuf field <code>.Vcloud.Models.Vod.VodGetPlayInfoResult Result = 2;</code>
     * @param \Vcloud\Models\Vod\Business\VodGetPlayInfoResult $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkMessage($var, \Vcloud\Models\Vod\Business\VodGetPlayInfoResult::class);
        $this->Result = $var;

        return $this;
    }

}

