<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vod/response/response_vod.proto

namespace Vcloud\Models\Vod\Response;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Vcloud.Models.Vod.VodGetVideoInfosResponse</code>
 */
class VodGetVideoInfosResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Vcloud.Models.Base.ResponseMetadata ResponseMetadata = 1;</code>
     */
    protected $ResponseMetadata = null;
    /**
     * Generated from protobuf field <code>.Vcloud.Models.Vod.VodGetVideoInfosData Result = 2;</code>
     */
    protected $Result = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Vcloud\Models\Base\ResponseMetadata $ResponseMetadata
     *     @type \Vcloud\Models\Vod\Business\VodGetVideoInfosData $Result
     * }
     */
    public function __construct($data = NULL) {
        \Vcloud\Models\GPBMetadata\ResponseVod::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Vcloud.Models.Base.ResponseMetadata ResponseMetadata = 1;</code>
     * @return \Vcloud\Models\Base\ResponseMetadata
     */
    public function getResponseMetadata()
    {
        return $this->ResponseMetadata;
    }

    /**
     * Generated from protobuf field <code>.Vcloud.Models.Base.ResponseMetadata ResponseMetadata = 1;</code>
     * @param \Vcloud\Models\Base\ResponseMetadata $var
     * @return $this
     */
    public function setResponseMetadata($var)
    {
        GPBUtil::checkMessage($var, \Vcloud\Models\Base\ResponseMetadata::class);
        $this->ResponseMetadata = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Vcloud.Models.Vod.VodGetVideoInfosData Result = 2;</code>
     * @return \Vcloud\Models\Vod\Business\VodGetVideoInfosData
     */
    public function getResult()
    {
        return $this->Result;
    }

    /**
     * Generated from protobuf field <code>.Vcloud.Models.Vod.VodGetVideoInfosData Result = 2;</code>
     * @param \Vcloud\Models\Vod\Business\VodGetVideoInfosData $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkMessage($var, \Vcloud\Models\Vod\Business\VodGetVideoInfosData::class);
        $this->Result = $var;

        return $this;
    }

}

